spring:
  application:
    name: Wagubook

  profiles:
    include: private

  h2:
    console:
      enabled: true
      path : /h2-console
  datasource:

#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password: 123
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://3.38.77.231:3306/wagubook?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: testId1
    password: testPw1
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create # application start
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

#  redis
#  로컬에서는 6379가 기본값이지만 운영,개발 서버는 redis의 host,port를 설정해야함
#  redis:
#    host: localhost
#    port: 6379


logging.level:
  org.hibernate.SQL: debug


OPENVIDU_URL: http://localhost:4443/
OPENVIDU_SECRET: MY_SECRET

server:
  servlet:
    session:
      cookie:
        domain: wagubook.shop
        same-site: none
        secure: true

