spring:
  application:
    name: Wagubook

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/book
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/querydsl
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # application start
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

#  redis
#  로컬에서는 6379가 기본값이지만 운영,개발 서버는 redis의 host,port를 설정해야함
  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug

