spring:
  application:
    name: Wagubook

  # h2:
  #   console:
  #     enabled: true
  datasource:
  #   url: jdbc:h2:tcp://localhost/~/book
  #   username: sa
  #   password:
  #   driver-class-name: org.h2.Driver
      url: jdbc:mysql://localhost:3306/querydsl
      username: testId1
      password: testPw1
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # application start
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug

